### PR TITLE
Types: Added type hints and cleaned up some type issues.

### PR DESCRIPTION
**Pull request by DrJKL**
Accidentally had the formatter running, so this is much noisier than I would like.
There are still a lot of Unknown types and it looks like pylance and opencv2 don't agree on some method signatures.

### CODE REVIEW

**Comment by WASasquatch** [comment]
Awesome work. 

Me and opencv don't get alone so I hear ya there. You can see that in my avoidance as much as possible. If PIL has a wrapper for it, I am gonna use it. Lol

**Comment by WASasquatch** [comment]
Alright. So stuck on mobile right now for awhile (out and about) and the web edit is apparently messed up. Can't compare to spot anything that needs fixing to merge. May be a bit.

**Comment by DrJKL** [comment]
Okay, merged the most recent changes at main

**Comment by WASasquatch** [comment]
Gotcha.

**Pull request merged**
