### PR TITLE
Improved text processing nodes

### LINKED ISSUE #303: [BUG] WAS_Text_List_Concatenate doesn't work at all
Hi, thanks a lot for this node pack. I'm working my way through the text nodes to try to make a dynamic prompt workflow. So far I'm using a bunch of `Text Multiline` nodes into a `Text List` node, which allows me to Bypass any `Text Multiline` boxes to rapidly toggle certain parts of the prompt.

All I need now is to convert that list of `["a", "b", "c"]` strings into a single comma-delimited String for use in prompting.

So I noticed that the `Text List` node's output is only compatible with the `WAS_Text_List_Concatenate` node. And I see that it has a "delimiter" input. So I assume that it's meant to turn the provided lists into a concatenated string.

If so, there are many bugs in the source code of the `WAS_Text_List_Concatenate` node:

1. The `delimiter` parameter is not used whatsoever. It's literally not used in the code at all.
2. The `delimiter` is marked as a REQUIRED parameter. But if we provide it, the node bugs with `WAS_Text_List_Concatenate.text_concatenate_list() got an unexpected keyword argument 'delimiter` because the node isn't coded properly to take that parameter, hehe.
3. The `list_b` is marked as a REQUIRED parameter too. If the purpose is to concatenate 1+ lists into a text string, it should only require the `list_a`. The rest should be optional.
4. The code forgot to actually convert the list to a STRING/TEXT. Because I assume that the entire purpose of the node is to take a bunch of lists and convert them to a normal string with a delimiter? Instead, it's just returning a concatenated list of all the given lists. I can't find any other nodes for turning the lists into a string.
5. It would be more convenient if `delimiter` was an internal text field (which can be converted to an input if needed), so we don't need to connect a separate `Text` node just to provide a delimiter.

PS: Adding a new, separate node that *is* able to concatenate lists would also be a good idea to complete the suite, basically to allow merging many separate `Text List` into one big list before concatenating it all into a text string with a final delimiter.

### PR DESCRIPTION
**Pull request by Arcitec**
See commits for changes. :heart: 

Closes #303

### CODE REVIEW

**Comment by Arcitec** [comment]
They've also been improved to make their inputs optional, which is more convenient (user can connect any inputs they want, and can Bypass/Mute inputs to skip certain ones).

**Comment by Arcitec** [comment]
Screenshots of the possibilities with the improved text nodes:

image

**Comment by WASasquatch** [comment]
Looks good! I don't have the time to test this week, but it looks good so I'll merge.

**Comment by Arcitec** [comment]
@WASasquatch I'm glad that I could help. I tested the nodes a bunch of times and of course the code isn't anything super complicated, so it should all be fine. :) Take care and have a nice Christmas!

**Comment by WASasquatch** [comment]
Thank you, Merry Christmas and Happy Holidays.

**Pull request merged**
