### PR TITLE
Prompt output for CLIP encoder

### PR DESCRIPTION
**Pull request by Radtoo**
I thought it was useful to have a text output on CLIPTextEncode to output the generated NSP/wildcard prompt and do things with it like save it in a companion .txt file, or other uses.

### CODE REVIEW

**Comment by WASasquatch** [comment]
Custom nodes can't output text to the API.

**Comment by Radtoo** [comment]
I don't know the ComfyUI API. This is for use in the UI same as I'd expect WAS to usually be used, to get the NSP/wildcard generated prompt text string.

**Comment by WASasquatch** [comment]
Yeah I think I get what ya mean now.

**Comment by WASasquatch** [comment]
image

Should be good to go now. You can `git pull`

**Comment by Radtoo** [comment]
Even better with the second output. Great!

**Pull request closed without merging**
